### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by ademilter** [ademilter/Frame#12]

**Comment by canaltinova** [comment]
If nobody is working, I would like to work on that. I checked the code and tried to install the addon directly to Firefox. There are some problems but overall it works. The problems I found are:

- `chrome.identity.getAuthToken` is not supported by Firefox since it's specific to Google.
We can use `chrome.identity.launchWebAuthFlow` for Firefox to implement that behavior. But that will require a bit more logic than just one `getAuthToken` call.
- The drag and drop is not working correctly. I think it's because the handler is button. It may be even a Firefox bug, I'm not sure yet.
- During dragging, the background of the card is not properly displayed.

I will try to fix and create a PR when I get a chance to work on that.
